language: python

dist: bionic

# https://devguide.python.org/#branchstatus
python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libgnutls28-dev

install:
  - pip install flake8 coverage
  - pip install coveralls
  - python setup.py install

script:
  - flake8 sentinel5dl
  - coverage run --source=sentinel5dl -m tests
  - coverage report

after_success:
  - pip install sphinx sphinx-rtd-theme
  - make -C docs clean html
  - touch docs/build/html/.nojekyll # create this file to prevent Github's Jekyll processing
  - coveralls

deploy:
  provider: pages
  fqdn: sentinel5dl.emissions-api.org
  verbose: true
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build/html
  on:
    branch: master
    python: "3.6"
    repo: emissions-api/sentinel5dl
